name: Docker Image CI

on:
  push:
    branches: ["main"]
    paths:
      - "Dockerfile"
      - "*.Dockerfile"
      - "**/*.Dockerfile"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: set env
        run: echo "NOW=$(TZ=Asia/Seoul date +'%Y.%m.%d')" >> $GITHUB_ENV

      - name: Set lowercase repository owner
        run: |
          repo_owner_lowercase=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_OWNER_LOWERCASE=$repo_owner_lowercase" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.REPO_OWNER_LOWERCASE }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build and Push (Cloudflare R2 Support)
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: |
            navystack/focalboard:cf-${{ env.NOW }}
            navystack/focalboard:cf
            ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/focalboard-ns:cf
            ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/focalboard-ns:cf-${{ env.NOW }}
          file: r2.Dockerfile
          platforms: linux/amd64,linux/arm64
          outputs: type=image,push=true

      - name: Docker Build and Push (with Nginx)
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: |
            navystack/focalboard:nginx-${{ env.NOW }}
            navystack/focalboard:nginx
            ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/focalboard-ns:nginx
            ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/focalboard-ns:nginx-${{ env.NOW }}
          file: Nginx.Dockerfile
          platforms: linux/amd64,linux/arm64
          outputs: type=image,push=true

      - name: Docker Build and Push (Focalboard Only)
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: |
            navystack/focalboard:latest-${{ env.NOW }}
            navystack/focalboard:8.0.0
            navystack/focalboard:latest
            ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/focalboard-ns:8.0.0
            ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/focalboard-ns:nginx-${{ env.NOW }}
            ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/focalboard-ns:latest
          platforms: linux/amd64,linux/arm64
          outputs: type=image,push=true
